# Generated by Django 3.1.6 on 2021-08-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_delete_userprofile'),
        ('users', '0002_auto_20210824_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pets.city'),
        ),
    ]
