# Generated by Django 3.1.6 on 2021-08-24 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='users',
            field=models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
