# Generated by Django 3.1.6 on 2021-08-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20210825_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='descripton',
            new_name='description',
        ),
    ]
